name: CI

on:
  push:
    branches: [ main ]         # cambia se il tuo branch principale ha un altro nome
  pull_request:
    branches: [ main ]
  workflow_dispatch:           # permette l’avvio manuale

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'   # cambia se serve Node 20

      - name: Install dependencies
        run: |
          if [ -f package-lock.json ]; then
            npm ci
          else
            npm install
          fi

      - name: Build (opzionale)
        run: |
          if npm run | grep -q " build"; then
            npm run build
          else
            echo "Nessuno script build, salto."
          fi

      - name: Test (opzionale)
        run: |
          if npm run | grep -q " test"; then
            npm test
          else
            echo "Nessuno script test, salto."
          fi
